export class CgiSymbol {
    // CGI Messages
    static readonly CGI_PROC_READ_METHOD_SELECT_NOT_SUPPORTED = "CGI_PROC_READ_METHOD_SELECT_NOT_SUPPORTED"
    static readonly CGI_PROC_READ_METHOD_SPIN_NOT_SUPPORTED = "CGI_PROC_READ_METHOD_SPIN_NOT_SUPPORTED"
}